### ISSUE TITLE
ConcurrentModificationException when used in multithreading way

### ISSUE THREAD

**Issue by rdebusscher** [soujava/microstream-jakarta-data#2]
Reading and writing is not properly 'shielded off' in a multithreaded environment.  You can read the data structure at the same time  MicroStream is persisting all data.

You can run `ConcurrencyIssue`  within the repo https://github.com/rdebusscher/microstream-data-issues to reproduce the _ConcurrentModificationException_.

**Comment by otaviojava** [comment]
Thanks @rdebusscher 

I've moved the the write operation to the sync, but I got this one, are you familiar with this issue?


Did you faced this issue?

```java
Caused by: one.microstream.storage.exceptions.StorageException: Problem in channel #0
	at one.microstream.storage.types.StorageChannelTask$Abstract.checkForProblems(StorageChannelTask.java:114)
	at one.microstream.storage.types.StorageChannelTask$Abstract.waitOnCompletion(StorageChannelTask.java:176)
	at one.microstream.storage.types.StorageRequestAcceptor$Default.waitOnTask(StorageRequestAcceptor.java:162)
	at one.microstream.storage.types.StorageRequestAcceptor$Default.storeData(StorageRequestAcceptor.java:180)
	at one.microstream.storage.embedded.types.EmbeddedStorageBinaryTarget$Default.write(EmbeddedStorageBinaryTarget.java:86)
	... 17 more
Caused by: java.lang.NullPointerException: Cannot invoke "one.microstream.storage.types.StorageLiveDataFile$Default.needsRetirement(one.microstream.storage.types.StorageDataFileEvaluator)" because "this.headFile" is null
	at one.microstream.storage.types.StorageFileManager$Default.checkForNewFile(StorageFileManager.java:563)
	at one.microstream.storage.types.StorageFileManager$Default.storeChunks(StorageFileManager.java:600)
	at one.microstream.storage.types.StorageChannel$Default.storeEntities(StorageChannel.java:548)
	at one.microstream.storage.types.StorageRequestTaskStoreEntities$Default.internalProcessBy(StorageRequestTaskStoreEntities.java:79)
	at one.microstream.storage.types.StorageRequestTaskStoreEntities$Default.internalProcessBy(StorageRequestTaskStoreEntities.java:46)
	at one.microstream.storage.types.StorageChannelTask$Abstract.processBy(StorageChannelTask.java:252)
	at one.microstream.storage.types.StorageChannel$Default.work(StorageChannel.java:409)
	at one.microstream.storage.types.StorageChannel$Default.run(StorageChannel.java:492)
	at java.base/java.lang.Thread.run(Thread.java:833)
Apr 13, 2023 7:02:41 PM org.jboss.weld.environment.se.WeldContainer shutdown
INFO: WELD-ENV-002001: Weld SE container 126e4617-046b-433b-b6f9-9960b9da7cfe shut down
```

**Comment by otaviojava** [comment]
The `StorageFileManager.headFile` is null on the method `checkForNewFile`

**Comment by rdebusscher** [comment]
I had that same error in combination with the `ConcurrentModificationException`.  That `ConcurrentModificationException` is no longer there but you still have the `NullPointerException` around the _headFile_?

Because I rewrote the example using just `StorageManager` and a root using `LazyHashMap` with all access to the `LazyHashMap` through synchronized methods and I don't have any exception (all works fine).

**Comment by otaviojava** [comment]
Mine returns the `ConcurrentModificationException`but it returns this issue because of the NPE.

Could you pull the sample using `StorageManager`? If you used any transversal approach, that could help.

I changed to Lazy instead of Eager the same issue.

**Comment by otaviojava** [comment]
Maybe also update this point of the documentation:
https://docs.microstream.one/manual/storage/root-instances.html

**Comment by rdebusscher** [comment]
See `LazyMapIssueDemo` in that same repo.

If not all reading and writing is synchronized on the some object (or using synchronized keyword in my case) you can end up with exceptions. Is indicated in the topic 'Shared Mutable Data' on the page you linked.

**Comment by otaviojava** [comment]
I got it, thanks.
I've updated it to use your approach; it works and became simpler; thanks.
https://github.com/ultimate-engineer/microstream-jakarta-data/pull/5
